language: python

python:
 - "2.7"

install:
 - pip install coverage coveralls pandas influxdb matplotlib numpy

script: 
 - coverage run --source=cryptoalgotrading setup.py test

after_success:
 - coveralls