language: python

python:
 - "3.7"

install:
 - pip install coverage coveralls pandas influxdb matplotlib numpy python-binance tables==3.5.2

script: 
 - coverage run --source=algotrading setup.py test

after_success:
 - coveralls
